# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: micwin.net Software-Entwicklung
email: michael.winkler@micwin.net
description: > # this means to ignore newlines until "baseurl:"
  java, ee, javaee, jee, j2ee, devops, swing, jenkins, maven, git, ant
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.micwin.net" # the base hostname & protocol for your site
twitter_username: micwin2
github_username:  micwin

# Build settings
markdown: kramdown
