# Site settings
title: Automation, Dev und Ops (und DevOps)
email: michael.winkler@gmx.de
description: > 
  Ansible, Azure, DevOps, Git, GitLab, GitLab-CI, Helm, Java, JEE, Jenkins, Kubernetes, Maven
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://micwin.github.io"
twitter_username: micwin2
github_username:  micwin
linkedin_username: micwin
telegram_username: micwin

# Build settings
markdown: kramdown
theme: jekyll-theme-merlot
