# Site settings
title: Automation, Dev und Ops (und DevOps)
email: michael.winkler@gmx.de
description: > 
  ansible, aure, devops, git, gitlab, gitlab-ci, helm, j2ee, java, javaee, jee, jenkins, 
  kubernetes, maven
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://micwin.github.io" # the base hostname & protocol for your site
twitter_username: micwin2
github_username:  micwin
linkedin_username: micwin
telegram_username: micwin

# Build settings
markdown: kramdown
